/**
 * Athlete Recipes - 50 High-Protein Muscle Building Recipes
 * Professional quality recipes for fitness enthusiasts
 */

import { RecipeMetadata } from '../../types/recipe';

// Athlete Recipe IDs
export const ATHLETE_RECIPE_IDS = [
  // Chicken Recipes (15)
  'grilled_chicken_breast_quinoa',
  'chicken_teriyaki_bowl',
  'mediterranean_chicken_wrap',
  'chicken_avocado_salad',
  'honey_garlic_chicken_rice',
  'chicken_fajita_bowl',
  'lemon_herb_chicken_vegetables',
  'chicken_tikka_masala',
  'bbq_chicken_sweet_potato',
  'greek_chicken_power_bowl',
  'chicken_broccoli_stir_fry',
  'cajun_chicken_pasta',
  'chicken_quinoa_stuffed_peppers',
  'asian_sesame_chicken_bowl',
  'chicken_shawarma_plate',
  
  // Beef Recipes (10)
  'beef_stir_fry_brown_rice',
  'lean_beef_burrito_bowl',
  'beef_vegetable_kebabs',
  'korean_beef_bowl',
  'beef_quinoa_meatballs',
  'steak_sweet_potato_meal',
  'beef_broccoli_garlic',
  'mediterranean_beef_rice',
  'beef_mushroom_stroganoff',
  'tex_mex_beef_skillet',
  
  // Fish & Seafood (10)
  'grilled_salmon_asparagus',
  'tuna_quinoa_salad',
  'cod_lemon_vegetables',
  'shrimp_garlic_zucchini',
  'salmon_teriyaki_bowl',
  'mediterranean_sea_bass',
  'tuna_steak_sweet_potato',
  'garlic_butter_shrimp_rice',
  'baked_tilapia_vegetables',
  'salmon_avocado_bowl',
  
  // Turkey Recipes (5)
  'turkey_quinoa_power_bowl',
  'turkey_vegetable_meatballs',
  'turkey_taco_lettuce_wraps',
  'herb_roasted_turkey_breast',
  'turkey_spinach_pasta',
  
  // Egg & Dairy Based (5)
  'protein_omelette_vegetables',
  'greek_yogurt_power_parfait',
  'cottage_cheese_protein_bowl',
  'egg_white_vegetable_scramble',
  'high_protein_breakfast_wrap',
  
  // Plant-Based High Protein (5)
  'chickpea_quinoa_power_bowl',
  'lentil_vegetable_curry',
  'black_bean_rice_bowl',
  'tofu_stir_fry_vegetables',
  'edamame_quinoa_salad',
] as const;

export type AthleteRecipeId = typeof ATHLETE_RECIPE_IDS[number];

// Recipe Metadata for all 50 athlete recipes
export const athleteRecipeMetadata: Record<AthleteRecipeId, RecipeMetadata> = {
  // ============================================
  // CHICKEN RECIPES (15)
  // ============================================
  grilled_chicken_breast_quinoa: {
    id: 'grilled_chicken_breast_quinoa',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'gluten_free', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400',
    iconName: 'fitness-outline',
    color: '#E53935',
    featured: true,
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  chicken_teriyaki_bowl: {
    id: 'chicken_teriyaki_bowl',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'quick', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1569058242567-93de6f36f8eb?w=400',
    iconName: 'restaurant-outline',
    color: '#FF5722',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  mediterranean_chicken_wrap: {
    id: 'mediterranean_chicken_wrap',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'mediterranean', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400',
    iconName: 'fast-food-outline',
    color: '#4CAF50',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  chicken_avocado_salad: {
    id: 'chicken_avocado_salad',
    isPremium: true,
    category: 'salad',
    difficulty: 'easy',
    tags: ['high_protein', 'low_carb', 'gluten_free', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1604909052743-94e838986d24?w=400',
    iconName: 'leaf-outline',
    color: '#8BC34A',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  honey_garlic_chicken_rice: {
    id: 'honey_garlic_chicken_rice',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400',
    iconName: 'restaurant-outline',
    color: '#FFC107',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  chicken_fajita_bowl: {
    id: 'chicken_fajita_bowl',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'gluten_free', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400',
    iconName: 'flame-outline',
    color: '#FF9800',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  lemon_herb_chicken_vegetables: {
    id: 'lemon_herb_chicken_vegetables',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'low_carb', 'gluten_free', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=400',
    iconName: 'leaf-outline',
    color: '#CDDC39',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  chicken_tikka_masala: {
    id: 'chicken_tikka_masala',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'gluten_free'],
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
    iconName: 'flame-outline',
    color: '#E65100',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  bbq_chicken_sweet_potato: {
    id: 'bbq_chicken_sweet_potato',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'gluten_free', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=400',
    iconName: 'bonfire-outline',
    color: '#BF360C',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  greek_chicken_power_bowl: {
    id: 'greek_chicken_power_bowl',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'mediterranean', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400',
    iconName: 'nutrition-outline',
    color: '#1976D2',
    featured: true,
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  chicken_broccoli_stir_fry: {
    id: 'chicken_broccoli_stir_fry',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'low_carb', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
    iconName: 'flame-outline',
    color: '#388E3C',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  cajun_chicken_pasta: {
    id: 'cajun_chicken_pasta',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=400',
    iconName: 'restaurant-outline',
    color: '#D32F2F',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  chicken_quinoa_stuffed_peppers: {
    id: 'chicken_quinoa_stuffed_peppers',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'gluten_free', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
    iconName: 'nutrition-outline',
    color: '#F44336',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  asian_sesame_chicken_bowl: {
    id: 'asian_sesame_chicken_bowl',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'quick', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400',
    iconName: 'restaurant-outline',
    color: '#795548',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  chicken_shawarma_plate: {
    id: 'chicken_shawarma_plate',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'mediterranean'],
    imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400',
    iconName: 'flame-outline',
    color: '#FF8F00',
    featured: true,
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  
  // ============================================
  // BEEF RECIPES (10)
  // ============================================
  beef_stir_fry_brown_rice: {
    id: 'beef_stir_fry_brown_rice',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=400',
    iconName: 'flame-outline',
    color: '#5D4037',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  lean_beef_burrito_bowl: {
    id: 'lean_beef_burrito_bowl',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'gluten_free', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1543352634-a1c51d9f1fa7?w=400',
    iconName: 'restaurant-outline',
    color: '#EF6C00',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  beef_vegetable_kebabs: {
    id: 'beef_vegetable_kebabs',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'low_carb', 'gluten_free'],
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400',
    iconName: 'flame-outline',
    color: '#C62828',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  korean_beef_bowl: {
    id: 'korean_beef_bowl',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1583224874284-0a94bd08c6a4?w=400',
    iconName: 'restaurant-outline',
    color: '#D84315',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  beef_quinoa_meatballs: {
    id: 'beef_quinoa_meatballs',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400',
    iconName: 'ellipse-outline',
    color: '#6D4C41',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  steak_sweet_potato_meal: {
    id: 'steak_sweet_potato_meal',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'gluten_free'],
    imageUrl: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400',
    iconName: 'fitness-outline',
    color: '#8D6E63',
    featured: true,
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  beef_broccoli_garlic: {
    id: 'beef_broccoli_garlic',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'low_carb', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1608039829572-29aa22f6acce?w=400',
    iconName: 'leaf-outline',
    color: '#33691E',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  mediterranean_beef_rice: {
    id: 'mediterranean_beef_rice',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'mediterranean', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
    iconName: 'restaurant-outline',
    color: '#0277BD',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  beef_mushroom_stroganoff: {
    id: 'beef_mushroom_stroganoff',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein'],
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400',
    iconName: 'restaurant-outline',
    color: '#4E342E',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  tex_mex_beef_skillet: {
    id: 'tex_mex_beef_skillet',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'gluten_free', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400',
    iconName: 'flame-outline',
    color: '#E65100',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  
  // ============================================
  // FISH & SEAFOOD (10)
  // ============================================
  grilled_salmon_asparagus: {
    id: 'grilled_salmon_asparagus',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'low_carb', 'gluten_free'],
    imageUrl: 'https://images.unsplash.com/photo-1485921325833-c519f76c4927?w=400',
    iconName: 'fish-outline',
    color: '#FF7043',
    featured: true,
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  tuna_quinoa_salad: {
    id: 'tuna_quinoa_salad',
    isPremium: true,
    category: 'salad',
    difficulty: 'easy',
    tags: ['high_protein', 'gluten_free', 'meal_prep', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1623855244183-52fd8d3ce2f7?w=400',
    iconName: 'fish-outline',
    color: '#42A5F5',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  cod_lemon_vegetables: {
    id: 'cod_lemon_vegetables',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'low_carb', 'gluten_free', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400',
    iconName: 'fish-outline',
    color: '#64B5F6',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  shrimp_garlic_zucchini: {
    id: 'shrimp_garlic_zucchini',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'low_carb', 'gluten_free', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=400',
    iconName: 'restaurant-outline',
    color: '#FF8A65',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  salmon_teriyaki_bowl: {
    id: 'salmon_teriyaki_bowl',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?w=400',
    iconName: 'fish-outline',
    color: '#E64A19',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  mediterranean_sea_bass: {
    id: 'mediterranean_sea_bass',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'mediterranean', 'gluten_free'],
    imageUrl: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=400',
    iconName: 'fish-outline',
    color: '#0288D1',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  tuna_steak_sweet_potato: {
    id: 'tuna_steak_sweet_potato',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'gluten_free'],
    imageUrl: 'https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?w=400',
    iconName: 'fish-outline',
    color: '#D81B60',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  garlic_butter_shrimp_rice: {
    id: 'garlic_butter_shrimp_rice',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'gluten_free', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1633504581786-316c8002b1b9?w=400',
    iconName: 'restaurant-outline',
    color: '#FFA726',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  baked_tilapia_vegetables: {
    id: 'baked_tilapia_vegetables',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'low_carb', 'gluten_free', 'budget_friendly'],
    imageUrl: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=400',
    iconName: 'fish-outline',
    color: '#26A69A',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  salmon_avocado_bowl: {
    id: 'salmon_avocado_bowl',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'gluten_free', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400',
    iconName: 'nutrition-outline',
    color: '#66BB6A',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  
  // ============================================
  // TURKEY RECIPES (5)
  // ============================================
  turkey_quinoa_power_bowl: {
    id: 'turkey_quinoa_power_bowl',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'gluten_free', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
    iconName: 'fitness-outline',
    color: '#8D6E63',
    featured: true,
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  turkey_vegetable_meatballs: {
    id: 'turkey_vegetable_meatballs',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'meal_prep', 'kid_friendly'],
    imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400',
    iconName: 'ellipse-outline',
    color: '#A1887F',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  turkey_taco_lettuce_wraps: {
    id: 'turkey_taco_lettuce_wraps',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'low_carb', 'gluten_free', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=400',
    iconName: 'leaf-outline',
    color: '#7CB342',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  herb_roasted_turkey_breast: {
    id: 'herb_roasted_turkey_breast',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'gluten_free', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1574672280600-4accfa5b6f98?w=400',
    iconName: 'restaurant-outline',
    color: '#795548',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  turkey_spinach_pasta: {
    id: 'turkey_spinach_pasta',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=400',
    iconName: 'restaurant-outline',
    color: '#43A047',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  
  // ============================================
  // EGG & DAIRY BASED (5)
  // ============================================
  protein_omelette_vegetables: {
    id: 'protein_omelette_vegetables',
    isPremium: true,
    category: 'breakfast',
    difficulty: 'easy',
    tags: ['high_protein', 'low_carb', 'gluten_free', 'quick', 'vegetarian'],
    imageUrl: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=400',
    iconName: 'sunny-outline',
    color: '#FFCA28',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  greek_yogurt_power_parfait: {
    id: 'greek_yogurt_power_parfait',
    isPremium: true,
    category: 'breakfast',
    difficulty: 'easy',
    tags: ['high_protein', 'gluten_free', 'quick', 'vegetarian'],
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
    iconName: 'layers-outline',
    color: '#EC407A',
    featured: true,
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  cottage_cheese_protein_bowl: {
    id: 'cottage_cheese_protein_bowl',
    isPremium: true,
    category: 'breakfast',
    difficulty: 'easy',
    tags: ['high_protein', 'low_carb', 'gluten_free', 'quick', 'vegetarian'],
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400',
    iconName: 'nutrition-outline',
    color: '#BDBDBD',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  egg_white_vegetable_scramble: {
    id: 'egg_white_vegetable_scramble',
    isPremium: true,
    category: 'breakfast',
    difficulty: 'easy',
    tags: ['high_protein', 'low_carb', 'gluten_free', 'quick', 'vegetarian'],
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400',
    iconName: 'sunny-outline',
    color: '#FDD835',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  high_protein_breakfast_wrap: {
    id: 'high_protein_breakfast_wrap',
    isPremium: true,
    category: 'breakfast',
    difficulty: 'easy',
    tags: ['high_protein', 'quick', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400',
    iconName: 'fast-food-outline',
    color: '#FF7043',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  
  // ============================================
  // PLANT-BASED HIGH PROTEIN (5)
  // ============================================
  chickpea_quinoa_power_bowl: {
    id: 'chickpea_quinoa_power_bowl',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'vegan', 'gluten_free', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400',
    iconName: 'leaf-outline',
    color: '#4CAF50',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  lentil_vegetable_curry: {
    id: 'lentil_vegetable_curry',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'vegan', 'gluten_free', 'budget_friendly'],
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    iconName: 'flame-outline',
    color: '#FF9800',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  black_bean_rice_bowl: {
    id: 'black_bean_rice_bowl',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'vegan', 'gluten_free', 'budget_friendly', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=400',
    iconName: 'restaurant-outline',
    color: '#37474F',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  tofu_stir_fry_vegetables: {
    id: 'tofu_stir_fry_vegetables',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'vegan', 'gluten_free', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    iconName: 'leaf-outline',
    color: '#8BC34A',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
  edamame_quinoa_salad: {
    id: 'edamame_quinoa_salad',
    isPremium: true,
    category: 'salad',
    difficulty: 'easy',
    tags: ['high_protein', 'vegan', 'gluten_free', 'quick', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=400',
    iconName: 'leaf-outline',
    color: '#26A69A',
    version: '1.0.0',
    lastUpdated: '2025-01-04',
  },
};

// Helper functions
export const getAthleteRecipeMetadata = (id: AthleteRecipeId): RecipeMetadata | undefined => {
  return athleteRecipeMetadata[id];
};

export const getAllAthleteRecipeMetadata = (): RecipeMetadata[] => {
  return ATHLETE_RECIPE_IDS.map(id => athleteRecipeMetadata[id]).filter((r): r is RecipeMetadata => r !== undefined && r !== null && typeof r.id === 'string');
};

export const getFeaturedAthleteRecipes = (): RecipeMetadata[] => {
  return getAllAthleteRecipeMetadata().filter(r => r && r.featured);
};

// Recipe Names
export const ATHLETE_RECIPE_NAMES: Record<AthleteRecipeId, { tr: string; en: string }> = {
  // Chicken
  grilled_chicken_breast_quinoa: { tr: 'Izgara Tavuk Göğsü & Kinoa', en: 'Grilled Chicken Breast & Quinoa' },
  chicken_teriyaki_bowl: { tr: 'Teriyaki Tavuk Bowl', en: 'Chicken Teriyaki Bowl' },
  mediterranean_chicken_wrap: { tr: 'Akdeniz Tavuk Wrap', en: 'Mediterranean Chicken Wrap' },
  chicken_avocado_salad: { tr: 'Tavuklu Avokado Salatası', en: 'Chicken Avocado Salad' },
  honey_garlic_chicken_rice: { tr: 'Ballı Sarımsaklı Tavuk & Pilav', en: 'Honey Garlic Chicken Rice' },
  chicken_fajita_bowl: { tr: 'Tavuk Fajita Bowl', en: 'Chicken Fajita Bowl' },
  lemon_herb_chicken_vegetables: { tr: 'Limonlu Otlu Tavuk & Sebzeler', en: 'Lemon Herb Chicken Vegetables' },
  chicken_tikka_masala: { tr: 'Tavuk Tikka Masala', en: 'Chicken Tikka Masala' },
  bbq_chicken_sweet_potato: { tr: 'BBQ Tavuk & Tatlı Patates', en: 'BBQ Chicken Sweet Potato' },
  greek_chicken_power_bowl: { tr: 'Yunan Usulü Tavuk Power Bowl', en: 'Greek Chicken Power Bowl' },
  chicken_broccoli_stir_fry: { tr: 'Tavuk Brokoli Stir Fry', en: 'Chicken Broccoli Stir Fry' },
  cajun_chicken_pasta: { tr: 'Cajun Tavuklu Makarna', en: 'Cajun Chicken Pasta' },
  chicken_quinoa_stuffed_peppers: { tr: 'Tavuklu Kinoa Dolma Biber', en: 'Chicken Quinoa Stuffed Peppers' },
  asian_sesame_chicken_bowl: { tr: 'Asya Usulü Susamlı Tavuk Bowl', en: 'Asian Sesame Chicken Bowl' },
  chicken_shawarma_plate: { tr: 'Tavuk Şavarma Tabağı', en: 'Chicken Shawarma Plate' },
  
  // Beef
  beef_stir_fry_brown_rice: { tr: 'Sığır Eti Stir Fry & Esmer Pirinç', en: 'Beef Stir Fry Brown Rice' },
  lean_beef_burrito_bowl: { tr: 'Yağsız Et Burrito Bowl', en: 'Lean Beef Burrito Bowl' },
  beef_vegetable_kebabs: { tr: 'Etli Sebze Kebabı', en: 'Beef Vegetable Kebabs' },
  korean_beef_bowl: { tr: 'Kore Usulü Et Bowl', en: 'Korean Beef Bowl' },
  beef_quinoa_meatballs: { tr: 'Etli Kinoa Köfte', en: 'Beef Quinoa Meatballs' },
  steak_sweet_potato_meal: { tr: 'Biftek & Tatlı Patates', en: 'Steak Sweet Potato Meal' },
  beef_broccoli_garlic: { tr: 'Sarımsaklı Et & Brokoli', en: 'Beef Broccoli Garlic' },
  mediterranean_beef_rice: { tr: 'Akdeniz Usulü Etli Pilav', en: 'Mediterranean Beef Rice' },
  beef_mushroom_stroganoff: { tr: 'Mantarlı Et Stroganoff', en: 'Beef Mushroom Stroganoff' },
  tex_mex_beef_skillet: { tr: 'Tex-Mex Et Tava', en: 'Tex Mex Beef Skillet' },
  
  // Fish & Seafood
  grilled_salmon_asparagus: { tr: 'Izgara Somon & Kuşkonmaz', en: 'Grilled Salmon Asparagus' },
  tuna_quinoa_salad: { tr: 'Ton Balıklı Kinoa Salatası', en: 'Tuna Quinoa Salad' },
  cod_lemon_vegetables: { tr: 'Limonlu Morina & Sebzeler', en: 'Cod Lemon Vegetables' },
  shrimp_garlic_zucchini: { tr: 'Sarımsaklı Karides & Kabak', en: 'Shrimp Garlic Zucchini' },
  salmon_teriyaki_bowl: { tr: 'Teriyaki Somon Bowl', en: 'Salmon Teriyaki Bowl' },
  mediterranean_sea_bass: { tr: 'Akdeniz Usulü Levrek', en: 'Mediterranean Sea Bass' },
  tuna_steak_sweet_potato: { tr: 'Ton Balığı Biftek & Tatlı Patates', en: 'Tuna Steak Sweet Potato' },
  garlic_butter_shrimp_rice: { tr: 'Tereyağlı Sarımsaklı Karides Pilav', en: 'Garlic Butter Shrimp Rice' },
  baked_tilapia_vegetables: { tr: 'Fırında Tilapia & Sebzeler', en: 'Baked Tilapia Vegetables' },
  salmon_avocado_bowl: { tr: 'Somon Avokado Bowl', en: 'Salmon Avocado Bowl' },
  
  // Turkey
  turkey_quinoa_power_bowl: { tr: 'Hindi Kinoa Power Bowl', en: 'Turkey Quinoa Power Bowl' },
  turkey_vegetable_meatballs: { tr: 'Sebzeli Hindi Köfte', en: 'Turkey Vegetable Meatballs' },
  turkey_taco_lettuce_wraps: { tr: 'Hindi Taco Marul Sarma', en: 'Turkey Taco Lettuce Wraps' },
  herb_roasted_turkey_breast: { tr: 'Otlu Fırın Hindi Göğsü', en: 'Herb Roasted Turkey Breast' },
  turkey_spinach_pasta: { tr: 'Hindili Ispanaklı Makarna', en: 'Turkey Spinach Pasta' },
  
  // Egg & Dairy
  protein_omelette_vegetables: { tr: 'Proteinli Sebzeli Omlet', en: 'Protein Omelette Vegetables' },
  greek_yogurt_power_parfait: { tr: 'Yunan Yoğurdu Power Parfait', en: 'Greek Yogurt Power Parfait' },
  cottage_cheese_protein_bowl: { tr: 'Lor Peynirli Protein Bowl', en: 'Cottage Cheese Protein Bowl' },
  egg_white_vegetable_scramble: { tr: 'Yumurta Akı & Sebze Karışımı', en: 'Egg White Vegetable Scramble' },
  high_protein_breakfast_wrap: { tr: 'Yüksek Proteinli Kahvaltı Wrap', en: 'High Protein Breakfast Wrap' },
  
  // Plant-Based
  chickpea_quinoa_power_bowl: { tr: 'Nohutlu Kinoa Power Bowl', en: 'Chickpea Quinoa Power Bowl' },
  lentil_vegetable_curry: { tr: 'Sebzeli Mercimek Köri', en: 'Lentil Vegetable Curry' },
  black_bean_rice_bowl: { tr: 'Siyah Fasulye Pilav Bowl', en: 'Black Bean Rice Bowl' },
  tofu_stir_fry_vegetables: { tr: 'Tofu & Sebze Stir Fry', en: 'Tofu Stir Fry Vegetables' },
  edamame_quinoa_salad: { tr: 'Edamame Kinoa Salatası', en: 'Edamame Quinoa Salad' },
};

// Nutrition info for each recipe (per serving)
export const ATHLETE_RECIPE_NUTRITION: Record<AthleteRecipeId, { calories: number; protein: number; carbs: number; fat: number }> = {
  // Chicken (high protein 35-50g)
  grilled_chicken_breast_quinoa: { calories: 450, protein: 45, carbs: 35, fat: 12 },
  chicken_teriyaki_bowl: { calories: 520, protein: 42, carbs: 55, fat: 14 },
  mediterranean_chicken_wrap: { calories: 480, protein: 38, carbs: 42, fat: 16 },
  chicken_avocado_salad: { calories: 420, protein: 36, carbs: 18, fat: 24 },
  honey_garlic_chicken_rice: { calories: 510, protein: 40, carbs: 58, fat: 12 },
  chicken_fajita_bowl: { calories: 465, protein: 42, carbs: 38, fat: 15 },
  lemon_herb_chicken_vegetables: { calories: 380, protein: 44, carbs: 22, fat: 14 },
  chicken_tikka_masala: { calories: 520, protein: 38, carbs: 45, fat: 20 },
  bbq_chicken_sweet_potato: { calories: 495, protein: 40, carbs: 52, fat: 12 },
  greek_chicken_power_bowl: { calories: 485, protein: 44, carbs: 40, fat: 16 },
  chicken_broccoli_stir_fry: { calories: 395, protein: 42, carbs: 24, fat: 14 },
  cajun_chicken_pasta: { calories: 540, protein: 38, carbs: 55, fat: 18 },
  chicken_quinoa_stuffed_peppers: { calories: 420, protein: 36, carbs: 38, fat: 14 },
  asian_sesame_chicken_bowl: { calories: 505, protein: 40, carbs: 50, fat: 16 },
  chicken_shawarma_plate: { calories: 490, protein: 42, carbs: 42, fat: 18 },
  
  // Beef (high protein 36-45g)
  beef_stir_fry_brown_rice: { calories: 520, protein: 38, carbs: 48, fat: 18 },
  lean_beef_burrito_bowl: { calories: 545, protein: 40, carbs: 52, fat: 16 },
  beef_vegetable_kebabs: { calories: 380, protein: 42, carbs: 18, fat: 16 },
  korean_beef_bowl: { calories: 510, protein: 36, carbs: 52, fat: 18 },
  beef_quinoa_meatballs: { calories: 440, protein: 38, carbs: 35, fat: 16 },
  steak_sweet_potato_meal: { calories: 520, protein: 45, carbs: 42, fat: 18 },
  beef_broccoli_garlic: { calories: 385, protein: 40, carbs: 20, fat: 16 },
  mediterranean_beef_rice: { calories: 495, protein: 38, carbs: 48, fat: 16 },
  beef_mushroom_stroganoff: { calories: 480, protein: 36, carbs: 42, fat: 20 },
  tex_mex_beef_skillet: { calories: 455, protein: 38, carbs: 35, fat: 18 },
  
  // Fish & Seafood (high protein 34-42g, omega-3)
  grilled_salmon_asparagus: { calories: 420, protein: 42, carbs: 12, fat: 24 },
  tuna_quinoa_salad: { calories: 385, protein: 38, carbs: 32, fat: 14 },
  cod_lemon_vegetables: { calories: 320, protein: 38, carbs: 18, fat: 10 },
  shrimp_garlic_zucchini: { calories: 295, protein: 34, carbs: 14, fat: 12 },
  salmon_teriyaki_bowl: { calories: 510, protein: 40, carbs: 48, fat: 18 },
  mediterranean_sea_bass: { calories: 380, protein: 38, carbs: 16, fat: 18 },
  tuna_steak_sweet_potato: { calories: 445, protein: 42, carbs: 38, fat: 14 },
  garlic_butter_shrimp_rice: { calories: 465, protein: 36, carbs: 52, fat: 14 },
  baked_tilapia_vegetables: { calories: 310, protein: 36, carbs: 20, fat: 10 },
  salmon_avocado_bowl: { calories: 480, protein: 38, carbs: 28, fat: 26 },
  
  // Turkey (lean protein 35-42g)
  turkey_quinoa_power_bowl: { calories: 465, protein: 42, carbs: 42, fat: 14 },
  turkey_vegetable_meatballs: { calories: 380, protein: 38, carbs: 28, fat: 14 },
  turkey_taco_lettuce_wraps: { calories: 320, protein: 36, carbs: 14, fat: 14 },
  herb_roasted_turkey_breast: { calories: 340, protein: 45, carbs: 8, fat: 14 },
  turkey_spinach_pasta: { calories: 485, protein: 38, carbs: 52, fat: 14 },
  
  // Egg & Dairy (protein 25-35g)
  protein_omelette_vegetables: { calories: 320, protein: 28, carbs: 12, fat: 18 },
  greek_yogurt_power_parfait: { calories: 380, protein: 32, carbs: 42, fat: 10 },
  cottage_cheese_protein_bowl: { calories: 295, protein: 30, carbs: 28, fat: 8 },
  egg_white_vegetable_scramble: { calories: 220, protein: 26, carbs: 10, fat: 8 },
  high_protein_breakfast_wrap: { calories: 420, protein: 32, carbs: 38, fat: 16 },
  
  // Plant-Based (protein 22-30g)
  chickpea_quinoa_power_bowl: { calories: 420, protein: 22, carbs: 58, fat: 12 },
  lentil_vegetable_curry: { calories: 385, protein: 24, carbs: 52, fat: 10 },
  black_bean_rice_bowl: { calories: 440, protein: 22, carbs: 68, fat: 8 },
  tofu_stir_fry_vegetables: { calories: 340, protein: 24, carbs: 28, fat: 16 },
  edamame_quinoa_salad: { calories: 380, protein: 22, carbs: 42, fat: 14 },
};
