/**
 * Recipe Metadata Configuration
 * Contains premium status, categories, and UI settings for all recipes
 */

import { RecipeMetadata, RecipeCategory, RECIPE_CATEGORIES } from '../../types/recipe';

// Recipe IDs - Add new recipes here
export const RECIPE_IDS = [
  // Kahvaltı
  'avocado_toast',
  'protein_pancakes',
  'overnight_oats',
  'veggie_omelette',
  'chia_pudding',
  'shakshuka',
  'acai_bowl',
  'turkish_menemen',
  
  // Ana Yemek
  'grilled_chicken_salad',
  'salmon_vegetables',
  'turkey_meatballs',
  'stuffed_peppers',
  'lentil_curry',
  'quinoa_bowl',
  'baked_cod',
  'chicken_stir_fry',
  'butter_chicken',
  'lamb_kofta',
  'shrimp_garlic_pasta',
  'beef_bulgogi',
  'chicken_biryani',
  'falafel_wrap',
  
  // Çorba
  'lentil_soup',
  'chicken_vegetable_soup',
  'tomato_basil_soup',
  'broccoli_soup',
  'mushroom_soup',
  'pumpkin_soup',
  
  // Salata
  'greek_salad',
  'caesar_salad',
  'quinoa_salad',
  'tuna_salad',
  'fattoush_salad',
  'avocado_chickpea_salad',
  
  // Atıştırmalık
  'hummus',
  'energy_balls',
  'greek_yogurt_parfait',
  'veggie_sticks',
  'baba_ganoush',
  'stuffed_dates',
  
  // Smoothie
  'green_smoothie',
  'berry_smoothie',
  'protein_smoothie',
  'tropical_smoothie',
  'mango_lassi',
  'peanut_butter_banana_smoothie',
  
  // Tatlı (Sağlıklı)
  'banana_nice_cream',
  'dark_chocolate_mousse',
  'fruit_salad',
  'rice_pudding',
  'baklava_oatmeal',
] as const;

export type RecipeId = typeof RECIPE_IDS[number];

export const recipeMetadata: Record<RecipeId, RecipeMetadata> = {
  // ============================================
  // KAHVALTI
  // ============================================
  avocado_toast: {
    id: 'avocado_toast',
    isPremium: true,
    category: 'breakfast',
    difficulty: 'easy',
    tags: ['vegetarian', 'quick', 'high_protein'],
    imageUrl: 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?w=400',
    iconName: 'leaf-outline',
    color: '#66BB6A',
    featured: true,
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  protein_pancakes: {
    id: 'protein_pancakes',
    isPremium: true,
    category: 'breakfast',
    difficulty: 'easy',
    tags: ['high_protein', 'kid_friendly'],
    imageUrl: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=400',
    iconName: 'disc-outline',
    color: '#FFA726',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  overnight_oats: {
    id: 'overnight_oats',
    isPremium: true,
    category: 'breakfast',
    difficulty: 'easy',
    tags: ['vegetarian', 'meal_prep', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=400',
    iconName: 'time-outline',
    color: '#8D6E63',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  veggie_omelette: {
    id: 'veggie_omelette',
    isPremium: true,
    category: 'breakfast',
    difficulty: 'easy',
    tags: ['vegetarian', 'high_protein', 'low_carb', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=400',
    iconName: 'sunny-outline',
    color: '#FFCA28',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  chia_pudding: {
    id: 'chia_pudding',
    isPremium: true,
    category: 'breakfast',
    difficulty: 'easy',
    tags: ['vegan', 'gluten_free', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?w=400',
    iconName: 'nutrition-outline',
    color: '#7E57C2',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },

  // ============================================
  // ANA YEMEK
  // ============================================
  grilled_chicken_salad: {
    id: 'grilled_chicken_salad',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'low_carb', 'mediterranean'],
    imageUrl: 'https://images.unsplash.com/photo-1604909052743-94e838986d24?w=400',
    iconName: 'restaurant-outline',
    color: '#66BB6A',
    featured: true,
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  salmon_vegetables: {
    id: 'salmon_vegetables',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'mediterranean', 'gluten_free'],
    imageUrl: 'https://images.unsplash.com/photo-1485921325833-c519f76c4927?w=400',
    iconName: 'fish-outline',
    color: '#FF7043',
    featured: true,
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  turkey_meatballs: {
    id: 'turkey_meatballs',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'kid_friendly'],
    imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400',
    iconName: 'ellipse-outline',
    color: '#8D6E63',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  stuffed_peppers: {
    id: 'stuffed_peppers',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'gluten_free', 'mediterranean'],
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
    iconName: 'flame-outline',
    color: '#EF5350',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  lentil_curry: {
    id: 'lentil_curry',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['vegan', 'high_protein', 'budget_friendly'],
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    iconName: 'leaf-outline',
    color: '#FF9800',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  quinoa_bowl: {
    id: 'quinoa_bowl',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['vegan', 'high_protein', 'gluten_free', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400',
    iconName: 'bowl-outline',
    color: '#26A69A',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  baked_cod: {
    id: 'baked_cod',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'low_carb', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400',
    iconName: 'fish-outline',
    color: '#42A5F5',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  chicken_stir_fry: {
    id: 'chicken_stir_fry',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'quick', 'low_carb'],
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
    iconName: 'flame-outline',
    color: '#F57C00',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },

  // ============================================
  // ÇORBA
  // ============================================
  lentil_soup: {
    id: 'lentil_soup',
    isPremium: true,
    category: 'soup',
    difficulty: 'easy',
    tags: ['vegan', 'high_protein', 'budget_friendly', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
    iconName: 'cafe-outline',
    color: '#FF8A65',
    featured: true,
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  chicken_vegetable_soup: {
    id: 'chicken_vegetable_soup',
    isPremium: true,
    category: 'soup',
    difficulty: 'easy',
    tags: ['high_protein', 'low_carb', 'kid_friendly'],
    imageUrl: 'https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?w=400',
    iconName: 'cafe-outline',
    color: '#FFCA28',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  tomato_basil_soup: {
    id: 'tomato_basil_soup',
    isPremium: true,
    category: 'soup',
    difficulty: 'easy',
    tags: ['vegan', 'mediterranean', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1629978444712-69171da5381b?w=400',
    iconName: 'cafe-outline',
    color: '#EF5350',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  broccoli_soup: {
    id: 'broccoli_soup',
    isPremium: true,
    category: 'soup',
    difficulty: 'easy',
    tags: ['vegetarian', 'low_carb', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1637163048116-e61ed66b6ddf?w=400',
    iconName: 'cafe-outline',
    color: '#66BB6A',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },

  // ============================================
  // SALATA
  // ============================================
  greek_salad: {
    id: 'greek_salad',
    isPremium: true,
    category: 'salad',
    difficulty: 'easy',
    tags: ['vegetarian', 'mediterranean', 'quick', 'low_carb'],
    imageUrl: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?w=400',
    iconName: 'leaf-outline',
    color: '#4CAF50',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  caesar_salad: {
    id: 'caesar_salad',
    isPremium: true,
    category: 'salad',
    difficulty: 'easy',
    tags: ['high_protein', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=400',
    iconName: 'leaf-outline',
    color: '#8BC34A',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  quinoa_salad: {
    id: 'quinoa_salad',
    isPremium: true,
    category: 'salad',
    difficulty: 'easy',
    tags: ['vegan', 'high_protein', 'gluten_free', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=400',
    iconName: 'leaf-outline',
    color: '#26A69A',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  tuna_salad: {
    id: 'tuna_salad',
    isPremium: true,
    category: 'salad',
    difficulty: 'easy',
    tags: ['high_protein', 'low_carb', 'quick', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1623855244183-52fd8d3ce2f7?w=400',
    iconName: 'fish-outline',
    color: '#42A5F5',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },

  // ============================================
  // ATIŞTIRMALIK
  // ============================================
  hummus: {
    id: 'hummus',
    isPremium: true,
    category: 'snack',
    difficulty: 'easy',
    tags: ['vegan', 'high_protein', 'mediterranean', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=400',
    iconName: 'ellipse-outline',
    color: '#FFCA28',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  energy_balls: {
    id: 'energy_balls',
    isPremium: true,
    category: 'snack',
    difficulty: 'easy',
    tags: ['vegan', 'high_protein', 'meal_prep', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=400',
    iconName: 'flash-outline',
    color: '#8D6E63',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  greek_yogurt_parfait: {
    id: 'greek_yogurt_parfait',
    isPremium: true,
    category: 'snack',
    difficulty: 'easy',
    tags: ['vegetarian', 'high_protein', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
    iconName: 'layers-outline',
    color: '#EC407A',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  veggie_sticks: {
    id: 'veggie_sticks',
    isPremium: true,
    category: 'snack',
    difficulty: 'easy',
    tags: ['vegan', 'low_carb', 'quick', 'kid_friendly'],
    imageUrl: 'https://images.unsplash.com/photo-1640719028782-8230f1bdc56e?w=400',
    iconName: 'nutrition-outline',
    color: '#66BB6A',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },

  // ============================================
  // SMOOTHIE
  // ============================================
  green_smoothie: {
    id: 'green_smoothie',
    isPremium: true,
    category: 'smoothie',
    difficulty: 'easy',
    tags: ['vegan', 'gluten_free', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400',
    iconName: 'nutrition-outline',
    color: '#4CAF50',
    featured: true,
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  berry_smoothie: {
    id: 'berry_smoothie',
    isPremium: true,
    category: 'smoothie',
    difficulty: 'easy',
    tags: ['vegetarian', 'quick', 'high_protein'],
    imageUrl: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=400',
    iconName: 'nutrition-outline',
    color: '#AB47BC',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  protein_smoothie: {
    id: 'protein_smoothie',
    isPremium: true,
    category: 'smoothie',
    difficulty: 'easy',
    tags: ['vegetarian', 'high_protein', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=400',
    iconName: 'barbell-outline',
    color: '#795548',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  tropical_smoothie: {
    id: 'tropical_smoothie',
    isPremium: true,
    category: 'smoothie',
    difficulty: 'easy',
    tags: ['vegan', 'gluten_free', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1546039907-7fa05f864c02?w=400',
    iconName: 'sunny-outline',
    color: '#FF9800',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },

  // ============================================
  // TATLI (Sağlıklı)
  // ============================================
  banana_nice_cream: {
    id: 'banana_nice_cream',
    isPremium: true,
    category: 'dessert',
    difficulty: 'easy',
    tags: ['vegan', 'gluten_free', 'kid_friendly'],
    imageUrl: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=400',
    iconName: 'ice-cream-outline',
    color: '#FFCA28',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  dark_chocolate_mousse: {
    id: 'dark_chocolate_mousse',
    isPremium: true,
    category: 'dessert',
    difficulty: 'medium',
    tags: ['vegetarian', 'gluten_free'],
    imageUrl: 'https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=400',
    iconName: 'heart-outline',
    color: '#5D4037',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  fruit_salad: {
    id: 'fruit_salad',
    isPremium: true,
    category: 'dessert',
    difficulty: 'easy',
    tags: ['vegan', 'gluten_free', 'quick', 'kid_friendly'],
    imageUrl: 'https://images.unsplash.com/photo-1564093497595-593b96d80180?w=400',
    iconName: 'nutrition-outline',
    color: '#E91E63',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },

  // ============================================
  // YENİ PREMIUM TARİFLER
  // ============================================
  
  // Kahvaltı - Yeni
  shakshuka: {
    id: 'shakshuka',
    isPremium: true,
    category: 'breakfast',
    difficulty: 'easy',
    tags: ['vegetarian', 'high_protein', 'mediterranean', 'gluten_free'],
    imageUrl: 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=400',
    iconName: 'flame-outline',
    color: '#E53935',
    featured: true,
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  acai_bowl: {
    id: 'acai_bowl',
    isPremium: true,
    category: 'breakfast',
    difficulty: 'easy',
    tags: ['vegan', 'gluten_free', 'high_protein', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400',
    iconName: 'nutrition-outline',
    color: '#7B1FA2',
    featured: true,
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  turkish_menemen: {
    id: 'turkish_menemen',
    isPremium: true,
    category: 'breakfast',
    difficulty: 'easy',
    tags: ['vegetarian', 'high_protein', 'mediterranean', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1608039829572-6d78c02a8e4c?w=400',
    iconName: 'sunny-outline',
    color: '#FF5722',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },

  // Ana Yemek - Yeni
  butter_chicken: {
    id: 'butter_chicken',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'gluten_free'],
    imageUrl: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=400',
    iconName: 'restaurant-outline',
    color: '#FF6F00',
    featured: true,
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  lamb_kofta: {
    id: 'lamb_kofta',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'mediterranean', 'gluten_free'],
    imageUrl: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?w=400',
    iconName: 'flame-outline',
    color: '#8D6E63',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  shrimp_garlic_pasta: {
    id: 'shrimp_garlic_pasta',
    isPremium: true,
    category: 'main_course',
    difficulty: 'easy',
    tags: ['high_protein', 'quick', 'mediterranean'],
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400',
    iconName: 'restaurant-outline',
    color: '#FF7043',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  beef_bulgogi: {
    id: 'beef_bulgogi',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['high_protein', 'dairy_free'],
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400',
    iconName: 'flame-outline',
    color: '#D32F2F',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  chicken_biryani: {
    id: 'chicken_biryani',
    isPremium: true,
    category: 'main_course',
    difficulty: 'hard',
    tags: ['high_protein', 'gluten_free', 'dairy_free'],
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
    iconName: 'restaurant-outline',
    color: '#FFA000',
    featured: true,
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  falafel_wrap: {
    id: 'falafel_wrap',
    isPremium: true,
    category: 'main_course',
    difficulty: 'medium',
    tags: ['vegan', 'high_protein', 'mediterranean'],
    imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400',
    iconName: 'leaf-outline',
    color: '#7CB342',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },

  // Çorba - Yeni
  mushroom_soup: {
    id: 'mushroom_soup',
    isPremium: true,
    category: 'soup',
    difficulty: 'easy',
    tags: ['vegetarian', 'low_carb', 'gluten_free'],
    imageUrl: 'https://images.unsplash.com/photo-1636489953081-c4ebde50e0df?w=400',
    iconName: 'cafe-outline',
    color: '#795548',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  pumpkin_soup: {
    id: 'pumpkin_soup',
    isPremium: true,
    category: 'soup',
    difficulty: 'easy',
    tags: ['vegan', 'gluten_free', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
    iconName: 'cafe-outline',
    color: '#FF9800',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },

  // Salata - Yeni
  fattoush_salad: {
    id: 'fattoush_salad',
    isPremium: true,
    category: 'salad',
    difficulty: 'easy',
    tags: ['vegan', 'mediterranean', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
    iconName: 'leaf-outline',
    color: '#689F38',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  avocado_chickpea_salad: {
    id: 'avocado_chickpea_salad',
    isPremium: true,
    category: 'salad',
    difficulty: 'easy',
    tags: ['vegan', 'high_protein', 'gluten_free', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400',
    iconName: 'leaf-outline',
    color: '#558B2F',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },

  // Atıştırmalık - Yeni
  baba_ganoush: {
    id: 'baba_ganoush',
    isPremium: true,
    category: 'snack',
    difficulty: 'medium',
    tags: ['vegan', 'mediterranean', 'gluten_free', 'meal_prep'],
    imageUrl: 'https://images.unsplash.com/photo-1541379889336-70f26e4c4617?w=400',
    iconName: 'ellipse-outline',
    color: '#8D6E63',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  stuffed_dates: {
    id: 'stuffed_dates',
    isPremium: true,
    category: 'snack',
    difficulty: 'easy',
    tags: ['vegan', 'gluten_free', 'quick', 'high_protein'],
    imageUrl: 'https://images.unsplash.com/photo-1582650949464-92f26dc95e9b?w=400',
    iconName: 'heart-outline',
    color: '#6D4C41',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },

  // Smoothie - Yeni
  mango_lassi: {
    id: 'mango_lassi',
    isPremium: true,
    category: 'smoothie',
    difficulty: 'easy',
    tags: ['vegetarian', 'gluten_free', 'quick', 'high_protein'],
    imageUrl: 'https://images.unsplash.com/photo-1623065422544-b2e59e5d2c25?w=400',
    iconName: 'nutrition-outline',
    color: '#FFB300',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  peanut_butter_banana_smoothie: {
    id: 'peanut_butter_banana_smoothie',
    isPremium: true,
    category: 'smoothie',
    difficulty: 'easy',
    tags: ['vegetarian', 'high_protein', 'quick', 'gluten_free'],
    imageUrl: 'https://images.unsplash.com/photo-1553787499-6f9133860278?w=400',
    iconName: 'barbell-outline',
    color: '#A1887F',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },

  // Tatlı - Yeni
  rice_pudding: {
    id: 'rice_pudding',
    isPremium: true,
    category: 'dessert',
    difficulty: 'easy',
    tags: ['vegetarian', 'gluten_free', 'kid_friendly'],
    imageUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=400',
    iconName: 'heart-outline',
    color: '#FFECB3',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
  baklava_oatmeal: {
    id: 'baklava_oatmeal',
    isPremium: true,
    category: 'dessert',
    difficulty: 'easy',
    tags: ['vegetarian', 'high_protein', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1495214783159-3503fd1b572d?w=400',
    iconName: 'heart-outline',
    color: '#D4A373',
    featured: true,
    version: '1.0.0',
    lastUpdated: '2025-01-01',
  },
};

// Helper functions
export const getRecipeMetadata = (id: RecipeId): RecipeMetadata | undefined => {
  return recipeMetadata[id];
};

export const getAllRecipeMetadata = (): RecipeMetadata[] => {
  return RECIPE_IDS.map(id => recipeMetadata[id]);
};

export const getRecipesByCategory = (category: RecipeCategory): RecipeMetadata[] => {
  return getAllRecipeMetadata().filter(r => r.category === category);
};

export const getFeaturedRecipes = (): RecipeMetadata[] => {
  return getAllRecipeMetadata().filter(r => r.featured);
};

export const getRecipesByTag = (tag: string): RecipeMetadata[] => {
  return getAllRecipeMetadata().filter(r => r.tags.includes(tag as any));
};
