/**
 * Diet Metadata Configuration
 * Contains premium status, UI settings, and tags for all 20 diets
 */

import { DietMetadata, DietId, DIET_IDS } from '../../types/diet';

export const dietMetadata: Record<DietId, DietMetadata> = {
  mediterranean: {
    id: 'mediterranean',
    isPremium: true,
    preview: 'Akdeniz mutfağının sağlıklı yağlar, sebzeler ve tam tahıllarla dolu beslenme yaklaşımı.',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['heart-healthy', 'balanced', 'sustainable'],
    goals: ['heart_health', 'weight_loss', 'longevity', 'brain_health'],
    difficulty: 'easy',
    duration: 'ongoing',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
    iconName: 'leaf-outline',
    color: '#4CAF50',
  },
  dash: {
    id: 'dash',
    isPremium: true,
    preview: 'Tansiyonu düşürmek için bilimsel olarak kanıtlanmış beslenme planı.',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['blood-pressure', 'heart-healthy', 'low-sodium'],
    goals: ['blood_pressure', 'heart_health', 'weight_loss'],
    difficulty: 'easy',
    duration: 'ongoing',
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400',
    iconName: 'heart-outline',
    color: '#E91E63',
  },
  mind: {
    id: 'mind',
    isPremium: true,
    preview: 'Beyin sağlığını destekleyen, Akdeniz ve DASH diyetlerinin birleşimi.',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['brain-health', 'cognitive', 'anti-aging'],
    goals: ['brain_health', 'longevity', 'heart_health'],
    difficulty: 'moderate',
    duration: 'ongoing',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    iconName: 'bulb-outline',
    color: '#9C27B0',
  },
  portfolio: {
    id: 'portfolio',
    isPremium: true,
    preview: 'Kolesterolü düşürmek için özel olarak tasarlanmış bitkisel ağırlıklı diyet.',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['cholesterol', 'plant-based', 'heart-healthy'],
    goals: ['ldl_cholesterol', 'heart_health'],
    difficulty: 'moderate',
    duration: 'ongoing',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400',
    iconName: 'analytics-outline',
    color: '#FF9800',
  },
  tlc: {
    id: 'tlc',
    isPremium: true,
    preview: 'Terapötik Yaşam Tarzı Değişiklikleri - kalp sağlığı odaklı beslenme.',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['therapeutic', 'cholesterol', 'lifestyle'],
    goals: ['ldl_cholesterol', 'heart_health', 'weight_loss'],
    difficulty: 'moderate',
    duration: 'ongoing',
    imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=400',
    iconName: 'medkit-outline',
    color: '#00BCD4',
  },
  nordic: {
    id: 'nordic',
    isPremium: true,
    preview: 'İskandinav mutfağından ilham alan, yerel ve mevsimsel beslenme.',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['scandinavian', 'sustainable', 'seasonal'],
    goals: ['sustainability', 'weight_loss', 'heart_health'],
    difficulty: 'easy',
    duration: 'ongoing',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400',
    iconName: 'snow-outline',
    color: '#607D8B',
  },
  japanese_style: {
    id: 'vegan',
    isPremium: true,
    preview: 'Tamamen bitkisel, hayvansal ürün içermeyen beslenme düzeni.',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['plant-based', 'ethical', 'sustainable'],
    goals: ['sustainability', 'heart_health', 'inflammation'],
    difficulty: 'advanced',
    duration: 'ongoing',
    imageUrl: 'https://images.unsplash.com/photo-1543362906-acfc16c67564?w=400',
    iconName: 'flower-outline',
    color: '#4CAF50',
  },
  wfpb: {
    id: 'wfpb',
    isPremium: true,
    preview: 'İşlenmemiş, tam gıdalardan oluşan bitkisel beslenme.',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['whole-foods', 'plant-based', 'unprocessed'],
    goals: ['heart_health', 'weight_loss', 'inflammation', 'diabetes_management'],
    difficulty: 'advanced',
    duration: 'ongoing',
    imageUrl: 'https://images.unsplash.com/photo-1490818387583-1baba5e638af?w=400',
    iconName: 'nutrition-outline',
    color: '#795548',
  },
  flexitarian: {
    id: 'flexitarian',
    isPremium: true,
    preview: 'Esnek vejeteryan - çoğunlukla bitkisel, ara sıra et içeren beslenme.',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['flexible', 'balanced', 'sustainable'],
    goals: ['sustainability', 'weight_loss', 'heart_health'],
    difficulty: 'easy',
    duration: 'ongoing',
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400',
    iconName: 'swap-horizontal-outline',
    color: '#009688',
  },
  pescatarian: {
    id: 'pescatarian',
    isPremium: true,
    preview: 'Deniz ürünleri ve bitkisel gıdalardan oluşan beslenme düzeni.',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['seafood', 'omega-3', 'balanced'],
    goals: ['heart_health', 'brain_health', 'weight_loss'],
    difficulty: 'easy',
    duration: 'ongoing',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400',
    iconName: 'fish-outline',
    color: '#03A9F4',
  },
  low_gi_gl: {
    id: 'low_gi_gl',
    isPremium: true,
    preview: 'Düşük glisemik indeksli gıdalarla kan şekeri kontrolü.',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['glycemic', 'blood-sugar', 'diabetes-friendly'],
    goals: ['glycemic_control', 'diabetes_management', 'weight_loss'],
    difficulty: 'moderate',
    duration: 'ongoing',
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400',
    iconName: 'trending-down-outline',
    color: '#FF5722',
  },
  diabetes_plate_carb: {
    id: 'diabetes_plate_carb',
    isPremium: true,
    preview: 'Diyabet yönetimi için tabak metodu ve karbonhidrat sayımı.',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['diabetes', 'carb-counting', 'portion-control'],
    goals: ['diabetes_management', 'glycemic_control', 'weight_loss'],
    difficulty: 'moderate',
    duration: 'ongoing',
    imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=400',
    iconName: 'pie-chart-outline',
    color: '#3F51B5',
  },
  low_carb: {
    id: 'low_carb',
    isPremium: true,
    preview: 'Karbonhidrat alımını azaltarak kilo kontrolü sağlayan beslenme.',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['low-carb', 'weight-loss', 'blood-sugar'],
    goals: ['weight_loss', 'glycemic_control', 'energy'],
    difficulty: 'moderate',
    duration: 'ongoing',
    imageUrl: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=400',
    iconName: 'remove-circle-outline',
    color: '#9E9E9E',
  },
  keto: {
    id: 'keto',
    isPremium: true,
    preview: 'Çok düşük karbonhidrat, yüksek yağlı ketojenik beslenme.',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['ketogenic', 'high-fat', 'very-low-carb'],
    goals: ['weight_loss', 'glycemic_control', 'energy'],
    difficulty: 'advanced',
    duration: '30 days',
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400',
    iconName: 'flame-outline',
    color: '#FF9800',
  },
  high_protein_deficit: {
    id: 'high_protein_deficit',
    isPremium: true,
    preview: 'Kas koruyarak yağ yakımı için yüksek proteinli kalori açığı.',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['high-protein', 'muscle-sparing', 'fat-loss'],
    goals: ['weight_loss', 'muscle_building'],
    difficulty: 'moderate',
    duration: '60 days',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    iconName: 'barbell-outline',
    color: '#F44336',
  },
  volumetrics: {
    id: 'volumetrics',
    isPremium: true,
    preview: 'Düşük kalori yoğunluklu, doyurucu gıdalarla kilo kontrolü.',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['volume-eating', 'satiety', 'low-calorie-density'],
    goals: ['weight_loss', 'gut_health'],
    difficulty: 'easy',
    duration: 'ongoing',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
    iconName: 'resize-outline',
    color: '#00BCD4',
  },
  time_restricted_eating: {
    id: 'time_restricted_eating',
    isPremium: true,
    preview: 'Günlük belirli saatler içinde yemek yeme (16:8 vb.).',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['intermittent-fasting', 'time-restricted', 'circadian'],
    goals: ['weight_loss', 'energy', 'longevity'],
    difficulty: 'moderate',
    duration: 'ongoing',
    imageUrl: 'https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400',
    iconName: 'time-outline',
    color: '#673AB7',
  },
  intermittent_fasting_5_2: {
    id: 'intermittent_fasting_5_2',
    isPremium: true,
    preview: 'Haftada 5 gün normal, 2 gün düşük kalorili beslenme.',
    version: '1.0.0',
    lastUpdated: '2025-01-01',
    tags: ['intermittent-fasting', '5-2', 'calorie-cycling'],
    goals: ['weight_loss', 'longevity', 'energy'],
    difficulty: 'advanced',
    duration: 'ongoing',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
    iconName: 'calendar-outline',
    color: '#E91E63',
  },
};

export const getDietMetadata = (id: DietId): DietMetadata | undefined => {
  return dietMetadata[id];
};

export const getAllDietMetadata = (): DietMetadata[] => {
  return DIET_IDS.map(id => dietMetadata[id]);
};

export const getPremiumDiets = (): DietMetadata[] => {
  return getAllDietMetadata().filter(d => d.isPremium);
};

export const getDietsByGoal = (goal: string): DietMetadata[] => {
  return getAllDietMetadata().filter(d => d.goals.includes(goal as any));
};
